sudo: false

language: d

os:
 - linux

d:
 - dmd-2.071.1

addons:
 apt:
  sources:
   - george-edison55-precise-backports # cmake 3.2.3 
  packages:
   - liblapack-dev
   - ffmpeg
   - cmake
   - cmake-data

before_install:
 - "export DISPLAY=:99.0"
 - sh -e /etc/init.d/xvfb start
 - chmod +x ./scripts/travis_lib_setup.sh

before_script:
 - ./scripts/travis_lib_setup.sh

script:
 - dub test -b unittest-cov

after_success:
  - bash <(curl -s https://codecov.io/bash)
