sudo: false

language: d

os:
 - linux

d:
 - dmd-2.070.0
 
before_install:
  - sudo apt-get install liblapack-dev
  - sudo apt-get install ffmpeg

script:
 - dub test -b unittest-cov

after_success:
  - bash <(curl -s https://codecov.io/bash)
