sudo: false

language: d

os:
 - linux

d:
 - dmd-2.070.0
 
addons:
 apt:
  packages:
   liblapack-dev

script:
  - dub test -b unittest-cov

after_success:
  - bash <(curl -s https://codecov.io/bash)
